name: Publish to Image Registry

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/appflowy-auth
          flavor: |
            latest=true
          tags: |
            type=raw,value=v${{ inputs.version }},enable=true
            type=raw,value=latest,enable=true

      - uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64

      - run: |
          set -ex

          echo "Adding explicit release version to Dockerfile..."

          sed -i 's/RELEASE_VERSION=unspecified/RELEASE_VERSION=${{ inputs.version }}/' Dockerfile

      - uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: docker/build-push-action@v3
        with:
          context: . # IMPORTANT: Dockerfile is modified above to include the release version. Don't remove this line: https://github.com/docker/build-push-action?tab=readme-ov-file#git-context
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
